---
title: "calucalte the variance explained"
output: NULL
author: "Jinliang Yang"
date: 10-20-2019
---

```{r setup}
# , include=TRUE, warning=FALSE, echo=TRUE, error=FALSE
knitr::opts_knit$set(root.dir=normalizePath('../../'))
knitr::opts_chunk$set(warning=FALSE, message=FALSE, error=FALSE, echo=TRUE)
```

# Read in the dataset

```{r}
# meta data
d <- read.csv("data/sample_data.csv")
d$Year <- paste0("Y", d$Year)
d$Block <- paste0("B", d$Block)
d$Rep <- paste0("R", d$Rep)

# ASV table
asv <- read.csv("data/ASV_table.csv")

## turn first column into rownames
asv2 <- asv[,-1]
rownames(asv2) <- asv[,1]
asv <- asv2
rm(asv2)

```

In total, we have 575 samples, each of them with `dim(asv)` ASV.


# Libraries

```{r}
library("lme4")
library("ggplot2")

```

### GMPR function to normailze ASV counts

### to calculates a "size factor" for each sample that can be used to normalize counts
### function: https://github.com/lichen-lab/GMPR/blob/master/GMPR.R
### examlpe: https://github.com/jchen1981/GMPR/blob/master/GMPR.Example.R
### paper: https://peerj.com/articles/4600.pdf


```{r}
require(matrixStats)

GMPR <- function (comm, intersect.no = 10, ct.min = 1, trace = TRUE) {
	# Computes the GMPR size factor
	#
	# Args:
	#   comm: a matrix of counts, row - features (OTUs, genes, etc) , column - sample
	#   intersect.no: the minimum number of shared features between sample pair, where the ratio is calculated
	#   ct.min: the minimum number of counts required to calculate ratios

	#
	# Returns:
	#   a vector of the size factors with attribute 'NSS'. Samples with distinct sets of features will be output as NA.
	#         NSS:   number of samples with significant sharing (> intersect.no) including itself
	
	# mask counts < ct.min
	comm[comm < ct.min] <- 0
	
	if (is.null(colnames(comm))) {
		colnames(comm) <- paste0('S', 1:ncol(comm))
	}
	
	if (trace) cat('Begin GMPR size factor calculation ...\n')
	
	comm.no <- numeric(ncol(comm))
	gmpr <- sapply(1:ncol(comm),  function(i) {		
				if (i %% 50 == 0) {
					cat(i, '\n')
				}
				x <- comm[, i]
				# Compute the pairwise ratio
				pr <- x / comm
				# Handling of the NA, NaN, Inf
				pr[is.nan(pr) | !is.finite(pr) | pr == 0] <- NA
				# Counting the number of non-NA, NaN, Inf
				incl.no <- colSums(!is.na(pr))		
				# Calculate the median of PR
				pr.median <- colMedians(pr, na.rm=TRUE)
				# Record the number of samples used for calculating the GMPR
				comm.no[i] <<- sum(incl.no >= intersect.no)
				# Geometric mean of PR median
				if (comm.no[i] > 1) {
					return(exp(mean(log(pr.median[incl.no >= intersect.no]))))
				} else {
					return(NA)
				}
			}
	)
	
	if (sum(is.na(gmpr))) {
		warning(paste0('The following samples\n ', paste(colnames(comm)[is.na(gmpr)], collapse='\n'), 
				'\ndo not share at least ', intersect.no, ' common taxa with the rest samples! ',
				'For these samples, their size factors are set to be NA! \n', 
				'You may consider removing these samples since they are potentially outliers or negative controls!\n',
				'You may also consider decreasing the minimum number of intersecting taxa and rerun the procedure!\n'))
	}
	
	if (trace) cat('Completed!\n')
	if (trace) cat('Please watch for the samples with limited sharing with other samples based on NSS! They may be outliers! \n')
	names(gmpr) <- names(comm.no) <- colnames(comm)
	
	attr(gmpr, 'NSS') <- comm.no
	
	return(gmpr)
}

```

# plotting functions

```{r}



### plot histogram of normalized ASV counts or diversity index

plot_hist <- function(d, aesx, title = ""){
  p <- ggplot(d, aes(x= aesx)) +
  geom_histogram(color = "black", fill="lightblue", position="dodge") +
  ggtitle(title) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5), axis.title.x = element_blank())
  return(p)
}



### plot percentage of variance explained from LMM fit

plot_varpc <- function(fit, title = ""){
  df <- as.data.frame(VarCorr(fit))
  df$p <- df$vcov/sum(df$vcov)*100
  df$grp <- factor(df$grp, levels = c("Year","Month","Species","Rotation","Nitrogen","Block","Rep","Residual"))
  
  p <- ggplot(df[-8, ], aes(x=grp, y=p, fill=grp))+
  geom_bar(stat="identity", color="black") +
    ggtitle(title) +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5), axis.title.x = element_blank())
  
  return(p)
}

```


# Seperate sample data and asv table by fractions

```{r}

# subset sample data
endo <- subset(d, Fraction %in% "Endosphere") #191
rhizo <- subset(d, Fraction %in% "Rhizosphere") #192
soil <- subset(d, Fraction %in% "Bulk Soil") #192

## subset asv table
asv_endo <- asv[, endo$Sample_ID]
asv_rhizo <- asv[, rhizo$Sample_ID]
asv_soil <- asv[, soil$Sample_ID]


```


### Log10-normailzed LMM

```{r}

### endo
fit <- lmer(data=endo, log10(ASV_counts+1) ~  (1|Year) + (1|Month) + (1|Species) + (1|Rotation) + (1|Nitrogen)  + (1|Block) + (1|Rep))
aesx = log10(endo$ASV_counts+1)
h_endo <- plot_hist(endo, aesx, "endo, Log10 normalized ASV counts")
p_endo <- plot_varpc(fit, title = "endo, Log10 normalized")


### rhizo
fit <- lmer(data=rhizo, log10(ASV_counts+1) ~  (1|Year) + (1|Month) + (1|Species) + (1|Rotation) + (1|Nitrogen)  + (1|Block) + (1|Rep))

aesx = log10(rhizo$ASV_counts+1)
h_rhizo <- plot_hist(rhizo, aesx, "rhizo, Log10 normalized ASV counts")
p_rhizo <- plot_varpc(fit, title = "rhizo, Log10 normalized")

### soil
fit <- lmer(data=soil, log10(ASV_counts+1) ~  (1|Year) + (1|Month) + (1|Species) + (1|Rotation) + (1|Nitrogen)  + (1|Block) + (1|Rep))

aesx = log10(soil$ASV_counts+1)
h_soil <- plot_hist(soil, aesx, "soil, Log10 normalized ASV counts")
p_soil <- plot_varpc(fit, title = "soil, Log10 normalized")



h_endo
h_rhizo
h_soil
```

```{r}
p_endo
p_rhizo
p_soil
```






### GMPR-normailzed LMM

```{r}

### endo
gmpr.size.factor <- GMPR(as.matrix(asv_endo))
fit <- lmer(data=endo, ASV_counts/c(gmpr.size.factor) ~  (1|Year) + (1|Month) + (1|Species) + (1|Rotation) + (1|Nitrogen)  + (1|Block) + (1|Rep))

aesx = (endo$ASV_counts)/c(gmpr.size.factor)
h_endo <- plot_hist(endo, aesx, "endo, GMPR normalized ASV counts")
p_endo <- plot_varpc(fit, title = "endo, GMPR normalized")

### rhizo
gmpr.size.factor <- GMPR(as.matrix(asv_rhizo))
fit <- lmer(data=rhizo, ASV_counts/c(gmpr.size.factor) ~  (1|Year) + (1|Month) + (1|Species) + (1|Rotation) + (1|Nitrogen)  + (1|Block) + (1|Rep))

aesx = (rhizo$ASV_counts)/c(gmpr.size.factor)
h_rhizo <- plot_hist(rhizo, aesx, "rhizo, GMPR normalized ASV counts")
p_rhizo <- plot_varpc(fit, title = "rhizo, GMPR normalized")

### soil
gmpr.size.factor <- GMPR(as.matrix(asv_soil))
fit <- lmer(data=soil, ASV_counts/c(gmpr.size.factor) ~  (1|Year) + (1|Month) + (1|Species) + (1|Rotation) + (1|Nitrogen)  + (1|Block) + (1|Rep))

aesx = (soil$ASV_counts)/c(gmpr.size.factor)
h_soil <- plot_hist(soil, aesx, "soil, GMPR normalized ASV counts")
p_soil <- plot_varpc(fit, title = "soil, GMPR normalized")


h_endo
h_rhizo
h_soil

```


```{r}
p_endo
p_rhizo
p_soil
```











